### ISSUE TITLE
Wrong reference doc in `_extensions.yml`

### ISSUE THREAD

**Issue by shirdekel** [wjschne/apaquarto#1]
When adding a template to an existing document using `quarto add wjschne/apaquarto`, rendering leads to the output reporting `File apa_processed.docx not found in resource path`. 

Changing `reference-doc: apa_processed.docx` to `reference-doc: apaquarto.docx` in `_extensions.yml` (which is actually in the directory) fixes it.

**Comment by wjschne** [comment]
Thanks for alerting me to this problem. The difference between `apa_processed.docx` and `apaquarto.docx`  is the running header. The officer package is used to insert the shorttitle field (in all caps) as the running header in the `apa_processed.docx` document. If the shorttitle field is not specified, the entire title is capitalized and inserted as the running header. I suspect that the reason the `apa_processed.docx` reference doc was not created for you was that I neglected to point out that this line needs to follow the document's YAML metadata:

`{{< include _extensions/wjschne/apaquarto/_apa_title.qmd >}}`

I have updated the README.md file to include this instruction.

Let me know if this fixes the problem.
