### ISSUE TITLE
Abstract Indendation

### ISSUE THREAD

**Issue by RobertEspo** [wjschne/apaquarto#101]
Thank you for the great template. It's extremely useful.

I noticed that back in April, you updated the code so that the abstract isn't indented. However, when I render to a .docx, the abstract is still indented. I'm not sure if I'm doing something wrong or if there's something up with the code. I checked the changes from April to now, and it doesn't seem like the part of the code you originally modified has since been changed. Thank you for any help!

**Comment by wjschne** [comment]
Not sure how this slipped past me. It has been updated.
