### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by agkamel** [wjschne/apaquarto#103]
Hi! I copy-pasted the minimal example of the README.qmd. When I tested it with my own document, the in-text citations were not working properly. I finally found that it was simply caused by a small typo, where it should be written `bibliography` instead of `bibliograpy`:

https://github.com/wjschne/apaquarto/blob/25b79d335b3e6f1236cd03e8bd052707a2e4c9ca/README.qmd#L156

It is a small detail, but since it took me some time to find out, I thought you'd like to know (especially for new users). I also found the same typo on the related website:

https://wjschne.github.io/apaquarto/installation.html#an-existing-file

...

(Unrelated: Thank you for this amazing template! The instructions on the website are very clear 💯)

**Comment by wjschne** [comment]
Thanks so much! The typo has been fixed.
