### ISSUE TITLE
Add apaquarto to awesome-quarto

### ISSUE THREAD

**Issue by NeubertJonas** [wjschne/apaquarto#14]
The apaquarto template could be added to the [awesome-quarto repo](https://github.com/mcanouil/awesome-quarto), which collects and showcases what is possible with Quarto. 

Apaquarto would fit under Templates > [Multiple Formats](https://github.com/mcanouil/awesome-quarto#multiple-formats), but I didn't want to add it without your permission.

**Comment by wjschne** [comment]
That would be fine! Thanks!

**Comment by wjschne** [comment]
I submitted the link.
