### ISSUE TITLE
Can't compile template

### ISSUE THREAD

**Issue by ihrke** [wjschne/apaquarto#18]
After updating to the newest version of apaquarto, I cannot compile the `template.qmd` file from the repository any more. 
This is the error message that comes up:

~~~
Quitting from lines 235-240 (template.qmd) 
Error in knitr::opts_current$lock(FALSE) : attempt to apply non-function
Calls: .main ... block_exec -> eng_r -> run_hooks -> do.call -> <Anonymous>
In addition: Warning message:
In do_once((if (is_R_CMD_check()) stop else warning)("The function xfun::isFALSE() will be deprecated in the future. Please ",  :
  The function xfun::isFALSE() will be deprecated in the future. Please consider using base::isFALSE(x) or identical(x, FALSE) instead.

Execution halted
~~~

When I delete all the r-chunks from the template, it compiles again.

**Comment by wjschne** [comment]
Sorry you are having trouble. Can you verify that you have the latest version of knitr?

**Comment by ihrke** [comment]
Oh, yes! After upgrading knitr, it works! Thanks for the help and thanks for providing this very nice extension!
