### ISSUE TITLE
block quotes

### ISSUE THREAD

**Issue by larkinrt** [wjschne/apaquarto#21]
Hi, thanks again for the hard work!

I am trying to do block quotes such as:

<img width="743" alt="image" src="https://github.com/wjschne/apaquarto/assets/24415194/74e5f7ae-2e40-4e6b-b7b9-b5a2065ced33">

The problem is the line after the paragraph is always indented upon rendering. I probably just don't know what command to use for the following line, been trying to google but to no avail. Is there an easy way to make the line after a block quote left justified (no indent)?

**Comment by wjschne** [comment]
Thanks for alerting me to this issue. I have added the ability to create paragraphs with no indenting. I demonstrated its use in the new template.qmd in the **Block Quotation** section. Basically, you enclose the paragraph in a div and give it a .NoIndent class:

```
:::{.NoIndent}
This paragraph will not be indented.
:::
```

**Comment by larkinrt** [comment]
Works great! Thank you for the prompt fix.

**Comment by wjschne** [comment]
Glad it worked!
