### ISSUE TITLE
No note under Figure makes improper spacing

### ISSUE THREAD

**Issue by larkinrt** [wjschne/apaquarto#22]
Hi again,

You already fixed the no note under table spacing in [issue 15](https://github.com/wjschne/apaquarto/issues/15), but now I noticed the same thing when using figures. Is there an easy fix for this too?

With note:
![with-note](https://github.com/wjschne/apaquarto/assets/24415194/916d9912-64e2-4397-bdf8-df779f67e4e3)

Without note:
![no-note](https://github.com/wjschne/apaquarto/assets/24415194/1b8fca62-f1b2-4b5f-8796-4446a666d001)

Thank you!

**Comment by wjschne** [comment]
I believe it is fixed now.

**Comment by larkinrt** [comment]
It is, thank you very much!
