### ISSUE TITLE
Bug with alphabetical sorting and e.g., in citations

### ISSUE THREAD

**Issue by larkinrt** [wjschne/apaquarto#23]
Apologies for the many posts. I promise one day I'll relearn coding to help improve useful projects like these.

`[e.g, @ettorre2016; @smith2012; @denzin2008a; @haraway1988; @ingersoll2016; @ngugiwathiongo1998]`

The above leads to a sorting issue where it appears in the text as the following:

(Denzin et al., 2008; e.g, Ettorre, 2016; Haraway, 1988; Ingersoll, 2016; Ngugi Wa Thiong’o, 1998; Smith, 2012)

**Comment by wjschne** [comment]
This turns out to be a feature of pandoc's citation syntax: All prefixes and suffixes stay with the citation they are next to. To get the result you are looking for, you will have to put the "e.g.,"next to denzin2008a or move denzin2008a to the first slot.
