### ISSUE TITLE
object 'is_pdf' not found on render

### ISSUE THREAD

**Issue by JohnFranchak** [wjschne/apaquarto#24]
When rendering a document with a table chunk, I get the following error:

```
processing file: activity_ema_ms.qmd
  |................................................    |  92% [apatb-demo]     
Quitting from lines 311-323 [apatb-demo] (activity_ema_ms.qmd)
Error:
! object 'is_pdf' not found
Backtrace:
  1. global .main()
 15. global `<fn>`(before = TRUE, options = `<kntr_st_>`)
                                                                                                            
Execution halted
```

It seems specific to the table. If I take out the table, everything renders OK. I get the error even if using the example table from the template:
```

```{r apatb-demo}
#| apa-cap: Here is the table caption.
#| apa-note: Here is the note below the table.
#| ft.align: left
 
tibble(Numbers = seq(1,4), Letters = LETTERS[seq(Numbers)]) %>% 
  flextable() %>% 
  theme_apa() %>% 
  line_spacing(part = "all") %>% 
  padding(padding.top = 5, padding.bottom = 5)

```
```

I'm not sure why it's happening. If I render the template without modifying anything, I can get the tables to work. But once I add in my own data I get these errors. If I run the chunks by themselves, there are no errors and I can see the preview of the flex_table I created.

**Comment by wjschne** [comment]
In the `_apa_title.qmd` file, the `is_pdf` object is to identify whether the file is a .pdf or not. It is assigned like so:

```r
is_pdf <- knitr::is_latex_output()
```

Can you run this line without error? I wonder if your knitr package needs to be updated. If not, feel free to send me your entire .qmd file and I will see if I can figure it out. My email is w.joel.schneider@gmail.com.

**Comment by JohnFranchak** [comment]
Thank you—I just realized that one of the external scripts I call to pre-process data was removing variables from the environment. I was inadvertently clearing out the "is_pdf" variable that was getting created. That fixed the problem.
