### ISSUE TITLE
Numbered lines

### ISSUE THREAD

**Issue by DominiqueMakowski** [wjschne/apaquarto#25]
Thanks for this very useful package. I was wondering if it was possible to add the option to have numbered lines? 

Thanks!

**Comment by wjschne** [comment]
If you only need line numbers in the pdf form, you can do so by adding this to the apaquarto-pdf yaml:

```yaml
include-in-header: 
      text: '\usepackage{lineno}\linenumbers'
```

If you need line numbers in the docx form, it is easy to add them:

https://support.microsoft.com/en-us/office/add-or-remove-line-numbers-b67cd35e-422c-42eb-adc9-256ca9802e22

**Comment by wjschne** [comment]
I added the numbered-lines option to the pdf yaml. 

```yaml
apaquarto-pdf:
  numbered-lines: true
```

**Comment by DominiqueMakowski** [comment]
Very cool, thanks a lot!
