### ISSUE TITLE
Trouble with apa_processed.docx

### ISSUE THREAD

**Issue by themaymon** [wjschne/apaquarto#29]
Hi! 
Thank you for developing this extension. I'm excited to implement this in my manuscript writing.
The error I have encountered is that I'm getting a message saying that "File apa_processed.docx not found in resource path".

I opened up _apa_title.qmd and found the part where you replace the headers in apaquarto.docx and print("apa_processed.docx") and I can confirm that apaquarto.docx is in the directory. But apa_processed.docx is not. 

PS. I apologise if I'm missing something obvious. I'm still learning.

**Comment by themaymon** [comment]
update: I manually made a copy of apaquarto.docx and named it apa_processed.docx in the same folder. This got rid of the error message and allowed the document to be produced. However, in the output document, there was no title page and abstract. The docx begins with the introductory paragraph.

**Comment by wjschne** [comment]
P.S. I am working on a new version of the extension that no longer needs to create a new reference file "apa_processed.docx" with every render. If I can figure everything out, I might even remove the need for the include shortcode.

**Comment by themaymon** [comment]
Thanks so much for the swift reply! And I'm excited to hear you're working on a new version :) 

I figured out the problem! So, you were correct that it had to do with the include shortcode, but it wasn't the spaces above/below. The problem was that for some reason my include shortcode had three curly brackets {} containing the statement, rather than two. I'm confused how that happened because I can see in your helpful example .qmd file that there were only two on each side. But anyhow, it's working like a charm now! 

Thank you so much for all the work you've done. I've been trying to make an APA 7 template for manuscript writing in quarto for my lab to use and your extension just does it all!
