### ISSUE TITLE
[Feature Request] CRediT Taxonomy

### ISSUE THREAD

**Issue by SHogenboom** [wjschne/apaquarto#3]
First of all: thanks for going through the trouble of creating a quarto APA template! Much appreciated and I’ve not encountered any major issues so far.

I was wondering if it would be possible to add the [CRediT (Contributor Roles Taxonomy)](https://credit.niso.org/)? The papaja [`papaja`](https://github.com/crsh/papaja) has already found a way to implement it, but my understanding of templates is not good enough to incorporate it myself.

Thanks in advance!

**Comment by wjschne** [comment]
This is a good idea. Are you aware of a standard way for APA format to include this information? It seems that including it in the third paragraph of the author note (or in a separate paragraph) is the natural home for this information.

**Comment by wjschne** [comment]
I implemented the feature. An example of its use is in the template. Let me know if it meets your needs.

**Comment by SHogenboom** [comment]
Thanks so much for implementing this right away! 

I’m having some issues where the affiliation superscript is now shown 5 times… which appears to correspond with the number of roles assigned. Will try and figure out what is happening. Struggling a bit with creating a minimal reproducible examples.
