### ISSUE TITLE
\tightlist error when rendering to pdf with lists

### ISSUE THREAD

**Issue by zheer-kejlberg** [wjschne/apaquarto#31]
Error message:
```

! Undefined control sequence.
I.213 \tightlist 
```

Can be fixed by adding 
```
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```
or just an empty tightlist definition:
`\def\tightlist{}`
to the before-body.tex file.

Hoping this can be added by default.

**Comment by wjschne** [comment]
Version 3.0.0 should have this fixed. Also, note the change to standard Quarto prefixes (fig- and tbl-). Also the include line below the metadata needs to be deleted. The extension will throw an informative error if it is left in.
