### ISSUE TITLE
Render fails when referneces but no citatoins

### ISSUE THREAD

**Issue by DominiqueMakowski** [wjschne/apaquarto#33]
An error showed up when I tried to render in pdf with no citations in the text (i.e., an empty ref list). Although it shoul'dnt happen quite often, it would be nice to not have it

```
ERROR: 
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.186 \end{CSLReferences}
                          

see manuscript.log for more information.
```

**Comment by DominiqueMakowski** [comment]
Or a more explicit error message, like : "can't build a reference with no citations in the text. Remove the reference building function or add a citation"

**Comment by wjschne** [comment]
Version 3.2.1 fixed the problem, I think. It removes the #refs div and the "References" heading if no citations are found.
