### ISSUE TITLE
Render to pdf fails: File `tcolorbox.sty' not found

### ISSUE THREAD

**Issue by tombeesley** [wjschne/apaquarto#35]
Hi - I can render the template to docx just fine, but pdf fails:

`LaTeX Error: File 'tcolorbox.sty' not found.`

**Comment by tombeesley** [comment]
Thanks Joel. Reinstalling tinytex seemed to fix it: `tinytex::reinstall_tinytex()`

**Comment by wjschne** [comment]
Great!
