### ISSUE TITLE
Quarto and apaquarto versions incompatibility

### ISSUE THREAD

**Issue by anastasiabright** [wjschne/apaquarto#39]
Hello Joel!

I would like to ask you if this issue is common for your extension, and if you have any idea, how to handle it?
I use R version 4.3.3, latest Quarto version 1.4 (the dev version goes also max up to 1.4.1...).

Thank you in advance for your reply!

```
> quarto::quarto_use_template("wjschne/apaquarto")
Quarto templates may execute code when documents are rendered.
• If you do not trust the author(s) of this Quarto templates, we recommend that you do not install or use this Quarto
  templates.
Do you trust the authors of this Quarto templates (Y/n)? Y
[>] Downloading
[>] Unzipping
[>] Copying files...
ERROR: The extension My Document in APA Style, Seventh Edition is incompatible with this quarto version.

Extension requires: >=1.4.549
Quarto version: 1.3.450

Error: The extension My Document in APA Style, Seventh Edition is incompatible with this quarto version.

Extension requires: >=1.4.549
Quarto version: 1.3.450
    at validateExtension (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:59608:15)
    at readExtension (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:59684:5)
    at async readExtensions (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:59457:35)
    at async readAndCopyExtensions (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:105016:24)
    at async copyExtensions (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:105013:5)
    at async file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:121630:17
    at async withSpinner (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:56614:9)
    at async useTemplate (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:121625:9)
    at async Command.fn (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:121609:9)
    at async Command.execute (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:8437:13)
Error in `quarto_use()`:
✖ Error running quarto cli.
Caused by error:
! System command 'quarto.exe' failed
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by wjschne** [comment]
It is confusing that the quarto package is not Quarto itself, but an interface for interacting with Quarto via the R console.

My best guess is that your quarto package is on version 1.4, but the underlying Quarto software on your machine is on version 1.3.450. 

If you update [Quarto](https://quarto.org/docs/get-started/), this problem should go away. Let me know what happens.

**Comment by anastasiabright** [comment]
I updated both Quarto and quarto package, and the installation was successfull via terminal! In RStudio still problematic.

Unfortunately, I just realised that this extension will probably not work on the project type 'book'... My idea was to separate each part of my thesis into different .qmd files for better overview. Maybe I have to switch to the combined document at some point.

Thank you!

**Comment by wjschne** [comment]
I'm glad the terminal worked. If you are writing a thesis, apaquarto would probably not give the best results. It is designed to create an APA manuscript that can be submitted to a journal. It would not likely conform to the requirements of your university. That said, there are parts of apaquarto that could be used selectively or adapted to achieve what you need. Let me know what you are hoping to achieve.

**Comment by anastasiabright** [comment]
At my institute we have indeed the thesis requirenments of the APA style. I assume, it is one of the learnings for students.
I will try to adopt apaquarto later to my structured thesis.
