### ISSUE TITLE
[Bug] Template doesn’t render

### ISSUE THREAD

**Issue by SHogenboom** [wjschne/apaquarto#4]
I was having some issues with author affiliations/abstracts/title after filling in the template - which I though was my doing. 

However, even when I try to render the template I’m getting an error:

```
Quitting from lines 172-581 (template.qmd) 
Error in `unnest()`:
! Can't subset columns that don't exist.
✖ Column `data` doesn't exist.
Backtrace:
  1. global f_author_affiliations(yml_metadata$author)
 19. tidyr:::unnest.data.frame(., data)
Warning message:
In do_once((if (is_R_CMD_check()) stop else warning)("The function xfun::isFALSE() will be deprecated in the future. Please ",  :
  The function xfun::isFALSE() will be deprecated in the future. Please consider using base::isFALSE(x) or identical(x, FALSE) instead.

Execution halted
```

Running:
```
R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Platform: x86_64-apple-darwin17.0 (64-bit)
```

Any help/fixes to the template would be appreciated!

**Comment by wjschne** [comment]
I am having trouble duplicating this error. I can imagine several problems. First, are you using updated versions of tidyverse packages (especially dplyr and tidyr)?

**Comment by SHogenboom** [comment]
It was indeed to do with using outdated pacakges. Forgot to update the `renv` lockfile. Apologies!

**Comment by wjschne** [comment]
Thanks! I will consider using code that does not use the latest features.
