### ISSUE TITLE
Clean extension template

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#41]
Hi! Thanks for all the great work so far 🙏

I just started a new manuscript project with `quarto use template wjschne/apaquarto` and it works fabulously 🚀. I'll probably use this more since Typst still is not quite ready to handle many APA requirements (looking at you, tables.)

Would it make sense to prune the template-provided files? I'd be happy to send a PR but since this is a bit of an opinion needs to be evaluated first. The following seem to clutter the end directory (created with `quarto use template wjschne/apaquarto`):

- `template.rmarkdown`
    - Does not serve a purpose
- `bibliography.bib` 
    - Could be provided but could be empty to avoid spurious references (depending on below)
    - It currently has 3 copies of the same reference
- `/img/`
    - Only needed for the example render of `<project-name>.qmd`
- `minimal.qmd` vs. `<project-name>.qmd`
    - _IMHO_ the latter is [documentation](https://wjschne.github.io/apaquarto/options.html) / example and not useful to the end user as a template

Additionally is there a way to rename the .Rproj file to <project-name> vs having it be `apaquarto.Rproj`?

**Comment by wjschne** [comment]
These are good suggestions. I implemented most of them. The `template.rmarkdown` now in the .gitignore filter. The img folder is no longer used. The `minimal.qmd` file became the `template.qmd` file. The old `template.qmd` file became `example.qmd`. I am not seeing any repeated entries in the `bibliography.bib` file: https://github.com/wjschne/apaquarto/blob/main/bibliography.bib

**Comment by mvuorre** [comment]
The template / example division makes sense and is probably helpful. I am sorry I made a typo previously, the template includes a spurious `references.bib` with the repeated entries. That file can probably be added to `.quartoignore` as well. `bibliography.bib` is fine.

(As a side note I like having the `.Rproj` included in the template but yeah maybe best to leave creating that to the users since this is a quarto template and not an RStudio template.)

Thanks for all the great work :)

**Comment by wjschne** [comment]
Done. `references.bib` added to .quartoignore

Thanks!
