### ISSUE TITLE
List extension at https://quarto.org/docs/extensions/listing-journals.html

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#42]
The instructions for including the extension at <https://quarto.org/docs/extensions/listing-journals.html> are at <https://github.com/quarto-dev/quarto-web/tree/main/docs/extensions/listings>.

Would be nice for visibility (for collaborators etc.)

Would be happy to help if this sounds interesting.

**Comment by wjschne** [comment]
Good idea! Submited pull request. I would love any help you can offer, particularly with a possible typst version.

**Comment by mvuorre** [comment]
Yeah it would be nice to include a typst format (`format: apaquarto-typst`) here instead of the separate repo at <https://github.com/mvuorre/quarto-apaish>. I am happy to submit an issue & PR for that?

**Comment by wjschne** [comment]
> Yeah it would be nice to include a typst format (`format: apaquarto-typst`) here instead of the separate repo at https://github.com/mvuorre/quarto-apaish. I am happy to submit an issue & PR for that?

Yes, thank you.

apaquarto is now listed on the Quarto site.
