### ISSUE TITLE
Typst template

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#44]
Following the note in #42 it might be of interest to provide a Typst format. I am happy to provide something like a `format: apaquarto-typst` to this extension, based on <https://github.com/mvuorre/quarto-apaish>. However, there's no Typst APA template (unlike the LaTeX APA7 package) and so that format would deviate somewhat from APA rules. Moreover it would be more limited in functionality as some needed/required features simply don't yet exist in Typst or its Quarto connection.

Given those limitations I'm happy to send a PR if you think it'd be useful, even as a starting point @wjschne 

(Some preliminary work on this at https://github.com/mvuorre/apaquarto/tree/typst.)

**Comment by wjschne** [comment]
Great! A PR would be nice. Which aspects of APA style will be the hardest to implement in Typst? Ideally, apaquarto should require no extra work on the user's part to render in the various formats. What excites me about the Typst format is that it renders quickly and presents opportunities for diverse display options (e.g., dissertations in APA-like formats).

**Comment by wjschne** [comment]
It is exciting to have a typst template! Thank you for getting it started. I made some initial changes to make various features work. I was able to make all the title, abstract, and citations work via the lua filters instead of using separate functions in Typst. I have not yet attempted to fix the figure  captions, but I believe I can make it work.

**Comment by wjschne** [comment]
@mvuorre, the figure and table captions are now working in typst. I imagine that there are many small problems that still need to be fixed, but the example.qmd rendered to typst looks good to me.
