### ISSUE TITLE
Feature Request-TOC in PDF

### ISSUE THREAD

**Issue by bsgallih12** [wjschne/apaquarto#45]
Hi! Is it possible to have table of contents generation possible in apaquarto-pdf? Also, is there an option in Word to put the TOC in a specific place. Right now it defaults to the first page and that's not where I want it

**Comment by wjschne** [comment]
I added the toc option for pdf (i.e., `toc: true` in the yaml). Let me know if it looks right and is in the right place. Keep in mind that APA style does not specify how a table of contents should look, and that any implication is thus non-standard. The placement of the table of contents in docx is not something apaquarto has direct control over. I will look for a solution. In the meantime, you can always make Word insert a table of contents at a custom location after the file has been generated. Put your cursor at the desired location and then in the "References" tab click "Table of Contents."

**Comment by bsgallih12** [comment]
Thanks for this! Is there a better place for potential feature requests?

**Comment by wjschne** [comment]
Not sure why. It is working on my end. Can you send the file (or the yaml at least)?

**Comment by bsgallih12** [comment]
I tried it again and it works this time. Also that is the perfect place to have it located. Thanks!

**Comment by wjschne** [comment]
Great! Let me know if anything else is needed.
