### ISSUE TITLE
[Bug]: apa_processed.docx

### ISSUE THREAD

**Issue by SHogenboom** [wjschne/apaquarto#5]
Everytime I render a document I get an additional document called `apa_processed.docx` which contains only one page with the shorttitle in the header. 

Perhaps this file needs to be removed again after all (pre-)processing has been completed?

**Comment by wjschne** [comment]
Yes, this is part of a hacky solution to the fact that Pandoc cannot change the header in the reference docx. I had to use the officer package to copy the pristine reference docx and insert a header. Let me see if I can delete the file after everything is rendered.

**Comment by SHogenboom** [comment]
I don’t mind hacky solutions if they work! So far I’ve enjoyed what you’ve been able to achieve greatly :)
