### ISSUE TITLE
inline citations fail to render

### ISSUE THREAD

**Issue by tombeesley** [wjschne/apaquarto#53]
I'm having an issue with inline citations rendering correctly. It happens for every reference. The ones is parentheses are rendering just fine, but every single inline reference fails to render. I'm assuming this is an issue with the template, since in a default quarto document they both render correctly.

![image](https://github.com/wjschne/apaquarto/assets/16871255/7e317a1f-cdcd-495e-bbd8-5fe4846d75b8)

<img width="312" alt="image" src="https://github.com/wjschne/apaquarto/assets/16871255/6c19f1c7-dd21-4e2c-8c61-fff81c5b0a44">

**Comment by wjschne** [comment]
If you update again, is the problem fixed?

**Comment by tombeesley** [comment]
Seems to be working perfectly now. Thanks!
