### ISSUE TITLE
Can't render example.qmd to typst

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#54]
I am at b49a553 and running `quarto render example.qmd --to apaquarto-typst --output example-typst.pdf` (Quarto v1.4.554) results in 

```bash
[typst]: Compiling example.typ to example.pdf...error: expected length, color, gradient, pattern, dictionary, stroke, or none, found function
    ┌─ example.typ:208:10
    │
208 │     stroke: (_, y) => (
    │ ╭───────────^
209 │ │       top: if y <= 1 { 0.5pt } else { 0pt },
210 │ │       bottom: 1pt,
211 │ │     )
    │ ╰─────^

help: error occurred in this call of function `article`
    ┌─ example.typ:318:14
    │
318 │   #show: doc => article(
    │ ╭───────────────^
319 │ │   runninghead: "TEMPLATE FOR THE APAQUARTO EXTENSION",
320 │ │   lang: "en",
321 │ │   doc,
322 │ │ )
    │ ╰─^
```

**Comment by wjschne** [comment]
Working fine for me. I think it is because I inadvertently used the newer table functions in Typst version 0.11.0. Is there a way to enforce the Typst version?

**Comment by mvuorre** [comment]
I see, and that Typst version is bundled with current pre-release Quarto. It also works for me on latest pre-release Quarto. 

IMHO it is safer to depend on a Quarto version than a specific version of each bundled tool (and I guess that should be the release version and not pre-release since many will just have the default install).

**Comment by wjschne** [comment]
I agree that the release version should be avoided. I am having trouble getting all the features to work without Typst 0.11.0. Specifically, I am having difficulty using conditional logic with counters. The counters are necessary for getting the appendix labels correct. The counters have always had a display method, but the get method was only recently introduced.

**Comment by mvuorre** [comment]
Righto! It might then be best to require Quarto 1.5.32 (current pre-release) or greater and introduce these features in a development branch. Then only merge to main once the required features are in standard Quarto. Allows you to both implement the features and not give headaches to end users who may not be running pre-release versions. Either way though the additions look sweet!

**Comment by wjschne** [comment]
The typst template now gives an informative error when the version is less than  0.11.0.
