### ISSUE TITLE
Start appendices on a new page

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#58]
As per APA7 rules (<https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/footnotes_appendices.html>).

(Happy to send a PR--feel free to assign.)

**Comment by mvuorre** [comment]
Thanks! Does it intentionally not do this for latex documents?

**Comment by wjschne** [comment]
Yes, the apa7 template inserts pagebreaks for each section after the `\appendix` command.

**Comment by mvuorre** [comment]
Sorry just to double check, I ran

```bash
quarto use template wjschne/apaquarto
quarto render example.qmd -t apaquarto-pdf -M documentmode:jou
```

And get this:

<img width="1098" alt="image" src="https://github.com/wjschne/apaquarto/assets/7349270/25714243-8c28-4c05-aa24-27352a571fe7">

Do you mean that journal mode PDFs should not start appendices on a new page?

**Comment by wjschne** [comment]
Yes. This behavior is controlled by the apa7 LaTeX package. It tends to follow the style of the Journal of Educational Psychology (an APA journal). I checked several articles with appendices. For example, [this one](https://dx.doi.org/10.1037/edu0000844) puts Appendix A on the same page as the references. It only starts an appendix on a new page when the content of an appendix does not fit on the remaining space on the page (e.g., [this paper]( https://dx.doi.org/10.1037/edu0000846))

**Comment by mvuorre** [comment]
Ooh, I see, thanks for clarifying! So even the APA does not follow the APA guidelines lol :)
