### ISSUE TITLE
Formatting errors in pdf output when `documentmode: doc`

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#59]
The PDF output is off when `documentmode: doc`:

<img width="755" alt="image" src="https://github.com/wjschne/apaquarto/assets/7349270/49fd84e0-78c2-4ed3-b80e-270d5342991c">

(Note I am on Quarto 1.4.554.)

**Comment by wjschne** [comment]
I made an initial fix, but there are float placement problems still.

**Comment by mvuorre** [comment]
Just adding a comment here (but sadly no reproducible example for manuscript is in prep): A very similar thing is happening with `documentmode: jou`. Text that should continue from the first page to the second disappears (including a basic table); second page begins a few paragraphs later. Removing the basic
