### ISSUE TITLE
Enable `include-in-header`

### ISSUE THREAD

**Issue by mvuorre** [wjschne/apaquarto#60]
It would be great to be able to use the [Quarto standard methods](https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes) for including LaTeX stuff, such as the `include-in-header` metadata field. However currently one must use a apaquarto custom (?) command `header-insert` to do so, which breaks interoperability and makes maintaining harder (?). See e.g. #40.

As a salient example, I would like to use the excellent [tinytable package](https://github.com/vincentarelbundock/tinytable), which automatically adds LaTeX requirements to the document (see 7.2 [here](https://vincentarelbundock.github.io/tinytable/vignettes/tinytable_tutorial.pdf)). However it doesn't work with apaquarto since it cannot use the standard Quarto methods for doing so. So for example the following would not work without lines 8-13 (which then do not propagate to other PDF formats):

````quarto
---
title: "My Title"
author:
  - name: Jane Doe
format:
  apaquarto-pdf:
    documentmode: doc
header-insert: |
  \usepackage{tabularray}
  \usepackage{float}
  \usepackage{graphicx}
  \usepackage[normalem]{ulem}
  \UseTblrLibrary{booktabs}
---

```{r}
library(knitr)
library(tinytable)
tbl <- mtcars[1:4, 1:4]
```

knitr::kable works

```{r}
kable(tbl)
```

tinytable::tt doesnt

```{r}
tt(tbl)
```
````

What features are blocking this and how can I help?

**Comment by wjschne** [comment]
Right now Quarto adds several additional things that break apaquarto whenever I allow this into the template. If you can figure out how to suppress Quarto's additions, let me know.

**Comment by wjschne** [comment]
Whatever the problem was before, it seems to be gone. I have now enabled `include-in-header`. Let me know if tinytable now works as you expect it to.

**Comment by mvuorre** [comment]
Yes, wonderful, works just fine now. 🎉

This

````quarto
---
title: "My Title"
author:
  - name: Jane Doe
format:
  apaquarto-pdf:
    documentmode: doc
---

```{r}
library(knitr)
library(tinytable)
tbl <- mtcars[1:4, 1:4]
```

knitr::kable works

```{r}
kable(tbl)
```

tinytable::tt does too!

```{r}
tt(tbl) |>
  theme_tt("placement", latex_float = "H")
```
````

Correctly produces this

<img width="763" alt="image" src="https://github.com/wjschne/apaquarto/assets/7349270/8bd3470c-aef4-4966-b017-d7cf314d8bd2">
