### ISSUE TITLE
All figures appear at the end of doc

### ISSUE THREAD

**Issue by schneiderpy** [wjschne/apaquarto#61]
Hi Joel. I'm not sure if this is a new "issue", but all my figures (produced by code or with knitr::include_graphics() ) appear at the end of the word document, and no matter if I reduce size / with / hight of the image (or is this APA 7th style?)

**Comment by wjschne** [comment]
Yes, this is typical of APA style. However, if you set `floatsintext: true` in your YAML header, the figures will be intermingled with your text. Let me know if this fixes your concern.

**Comment by schneiderpy** [comment]
Thank you @wjschne. This solved the issue
