### ISSUE TITLE
Problems with code listings

### ISSUE THREAD

**Issue by filippogambarota** [wjschne/apaquarto#62]
I have tried to add captions and cross referencing for code listings (https://quarto.org/docs/authoring/cross-references.html#code-listings) but I have an error:

In the default qmd file I've simply added:
```{r}
#| echo: true
#| lst-label: lst-code
#| lst-cap: My code
print("hello world")
```
But during rendering I have 

```
LaTeX Error: Environment codelisting undefined.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```

I have tried also to add `\usepackage{codelisting}` in the header but without success.

**Comment by wjschne** [comment]
Is it fixed now?

**Comment by wjschne** [comment]
Should code listing captions have the same format as figures and tables?

**Comment by filippogambarota** [comment]
Thank you now it works perfectly!
