### ISSUE TITLE
Typst Render Issue

### ISSUE THREAD

**Issue by bsgallih12** [wjschne/apaquarto#63]
Hi I'm using the typst format. When I do the render totally fails saying I need typst version 0.11. So I've installed it and it appears it's not recognizing I have it installed. Idk if that's an extension issue though or a RStudio issue. My command line says my typst version is the correct one

**Comment by wjschne** [comment]
My apologies. I thought that upgrading Typst would fix this problem. Unfortunately, Quarto uses its own version of Typst. To use apaquarto-typst, you would need to upgrade to the prerelease version of Quarto 1.5.

**Comment by bsgallih12** [comment]
Thank you!
