### ISSUE TITLE
Cross Referencing

### ISSUE THREAD

**Issue by bsgallih12** [wjschne/apaquarto#66]
Hello,

I'm not sure if this is a limitation or a bug but I can only do figure cross-referencing with the pdf output option. The Word, Typst, and HTML options are throwing an error when I try to invoke cross-referencing. Works perfectly fine on the PDF output though

**Comment by wjschne** [comment]
Is this fixed now?

**Comment by bsgallih12** [comment]
Hi. It doesn't look like it. I'm getting the following error:

Error running filter /Applications/quarto/share/filters/main.lua:
...ript/_extensions/wjschne/apaquarto/apafigtblappendix.lua:56: attempt to concatenate a nil value (field 'prefix')
stack traceback:
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:535: in local 'checked_walk'
	/Applications/quarto/share/filters/main.lua:587: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:1312: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/Applications/quarto/share/filters/main.lua:1328: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1366: in function </Applications/quarto/share/filters/main.lua:1363>
stack traceback:
	/Applications/quarto/share/filters/main.lua:535: in local 'checked_walk'
	/Applications/quarto/share/filters/main.lua:587: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:1312: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/Applications/quarto/share/filters/main.lua:1328: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1366: in function </Applications/quarto/share/filters/main.lua:1363>

**Comment by bsgallih12** [comment]
And for it I've told quarto to name the figure {#fig-corr1} and referenced it using @fig-corr1. If I take it out, everthing runs but only after adding the @fig-corr1 does it return an error

**Comment by bsgallih12** [comment]
It appears to still be an issue. It will run until I try to label a photo inside the document like shown below and then I reference it with @fig-corr. 

![](figure.png){fig-corr)

**Comment by wjschne** [comment]
I am not sure what you meant to display. `{fig-corr)` has no closing curly brace.

**Comment by bsgallih12** [comment]
Hi! So this is what I have in my .qmd file but when I got to render it won't. In case it helps. This is a child document, but even when I just try to render the individual .qmd file (attached here), it doesn't render correctly

<img width="871" alt="Screenshot 2024-05-13 at 12 39 34 PM" src="https://github.com/wjschne/apaquarto/assets/99361055/083ce571-c442-4a28-93d8-96e23359f26a">

**Comment by wjschne** [comment]
I see now! The apaquarto template assumes that all figures have captions. If you set the caption, it should work:

```md
![My Correlation Plot](Corr_Plot.png){#fig-corr1}
```

Do you need to make a figure without a caption?

**Comment by bsgallih12** [comment]
Oh I see! I don't have a pressing need to have one without a caption however if I did need one what would I need to do?

**Comment by wjschne** [comment]
For a rock-solid solution, I would need to reconfigure the Lua filters. For a temporary solution, you can try putting in a non-printing character (e.g, a non-breaking space:  `&nbsp;`)
