### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by schneiderpy** [wjschne/apaquarto#67]
Hi Joel. I'm not sure if there's a possibility to use the current extension for APA 7th ed. (no ampersand) style?

**Comment by wjschne** [comment]
I am not sure if I can make that work. However, most of the functions from that style have been implemented in apaquarto:

1. It automatically removes the ampersand from in-text references.
2. You can specify a different word instead of "and" like so:

```yaml
language:
  citation-last-author-separator: "et"
```

Is there something else that is needed?

**Comment by schneiderpy** [comment]
The automatical removel of the ampersand does not work in my case (visual editor, both options ticked and unticked in-text option)

**Comment by wjschne** [comment]
I do not work with the visual editor. Does it show formatted citations? If so, apaquarto only fixes the citations after rendering. 

Also, apaquarto removes the ampersand in the in-text citations, not in the references section (that would violate APA style). Is there a need to replace ampersands in the references section?

**Comment by wjschne** [comment]
If the ampersand removal does not work at all, then I would probably need to see your .qmd file (or a minimal example) to figure out what is going wrong.

**Comment by schneiderpy** [comment]
Where can I send you the yaml header of the .qmd file?

**Comment by wjschne** [comment]
You can send it to schneider@temple.edu

**Comment by wjschne** [comment]
Added `no_ampersand_parenthetical` option.
