### ISSUE TITLE
Questions About Customizing APA Format

### ISSUE THREAD

**Issue by baker-jr-john** [wjschne/apaquarto#68]
First, I appreciate your helping others format their reports in APA style. I have a few questions and would appreciate your assistance:

1. Is there a way to suppress the title in the header on every page?

<img width="1516" alt="header-title" src="https://github.com/wjschne/apaquarto/assets/71906203/53a5f7e2-425d-4d56-98ad-fc1e8b8a53cc">

2. Can the page number on *only* the first page be suppressed? 

<img width="1516" alt="header-page-number" src="https://github.com/wjschne/apaquarto/assets/71906203/9755bedb-c9a3-4cc3-9822-68d186658d40">

3. Is it possible to suppress the author's note?

<img width="1548" alt="author-note" src="https://github.com/wjschne/apaquarto/assets/71906203/19e01ea1-d157-4c30-8a77-3fda284d7e4d">

Please let me know if there's a more appropriate place to post these questions. I appreciate your help!

**Comment by wjschne** [comment]
I just added the ability to suppress many aspects of the title page.  See [template options](https://wjschne.github.io/apaquarto/options.html#suppress-elements) for details. In your case, you would set `suppress-short-title: true` to suppress the running header, and `suppress-author-note: true` to suppress the Author Note. Suppressing the page number on the first page might be possible, but I have not yet figured how to do it.

**Comment by baker-jr-john** [comment]
Unfortunately, the title header is still displayed on all of the pages, and the author's note is still present.

I'm using apaquarto version 4.1.0. Here is the YAML for my document.

---
title: "Examining Changes in Patient Satisfaction During the COVID-19 Pandemic: An Analysis of HCAHPS Scores"
author:
  - name: John Baker
    affiliations:
      - id: sunynp
  - name: Tyler Eisloeffel
    affiliations:
      - id: sunynp
  - name: Justin Martin
    affiliations:
      - id: sunynp
  - name: Juncheng Shi
    affiliations:
      - id: sunynp
affiliations:
  - id: sunynp
    name: SUNY New Paltz
format:
  apaquarto-pdf:
    documentmode: stu
    course: "BUS461-01: Business Analytics Capstone"
    professor: Professor Tao Li
    duedate: May 14, 2024
    draftfirst: true
    suppress-short-title: true
    suppress-author-note: true
lang: en
language: 
  title-block-correspondence-note: ~
execute:
  echo: true
  freeze: true
---
Can you please let me know if I'm doing anything wrong or if you need more information? I appreciate it!

**Comment by wjschne** [comment]
I am not sure what the problem might be. It is working well on my machine. Perhaps, at least once, you need to set `freeze: false`? Also, I have noticed lately that my pdf viewer does not always refresh automatically. Try refreshing it manually (or try closing and reopening RStudio). If neither of those solutions works, I am happy to meet over Zoom to see what else might be going on.

**Comment by wjschne** [comment]
No problem. Send some times you have available to schneider@temple.edu, and I will pick one.

**Comment by baker-jr-john** [comment]
Please don't worry about how to suppress the page number on the first page. I thought that was part of APA guidelines, but I was mistaken. I'm excited to meet with you to sort through the other issues.

**Comment by wjschne** [comment]
Problem fixed in consultation meeting.
