### ISSUE TITLE
lang es does not render

### ISSUE THREAD

**Issue by schneiderpy** [wjschne/apaquarto#76]
@wjschne I have an apaquarto issue as follow:
I have a yaml for a document in english language which renders fine. Now, I just changed lang: es .. and get an error:

```
> # Language options. See https://quarto.org/docs/authoring/language.html
> lang: es
> language: 
>   section-title-appendix: "Apéndice"
>   title-block-author-note: "Nota de Autores"
>   title-block-correspondence-note: "La correspondencia relativa a este artículo debe dirigirse a"
> format:
>   apaquarto-docx: default
>   apaquarto-html: default
>   #apaquarto-pdf:
>     # Can be jou (journal), man (manuscript), stu (student), or doc (document)
>      #documentmode: man
```
```
 crossref:
    fig-title: Fig.
    tbl-title: Table
    title-delim: ' '
  numbered-lines: false
  lang: es

Error running filter C:/Users/Acer/AppData/Local/Programs/Quarto/share/filters/main.lua:
string expected, got nil
	while retrieving function argument text
	while retrieving arguments for function Str
stack traceback:
	...ject\_extensions\wjschne\apaquarto\apafigtblappendix.lua:72: in function <...ject\_extensions\wjschne\apaquarto\apafigtblappen
```

**Comment by wjschne** [comment]
I'm afraid I can't duplicate this error by changing the `lang` field to `es` in my default document. Can you post a minimal example that produces the error?

**Comment by schneiderpy** [comment]
Well, I don't know which part of the document produces the error.
I'll paste the entire error message, and, hopfully you can point me to the direction where to look at ..

> Error running filter C:/Users/Acer/AppData/Local/Programs/Quarto/share/filters/main.lua:
> string expected, got nil
> 	while retrieving function argument text
> 	while retrieving arguments for function Str
> stack traceback:
> 	...ject\_extensions\wjschne\apaquarto\apafigtblappendix.lua:72: in function <...ject\_extensions\wjschne\apaquarto\apafigtblappendix.lua:34>
> 	[C]: in ?
> 	[C]: in method 'walk'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:225: in local 'checked_walk'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:277: in function 'run_emulated_filter'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:981: in local 'callback'
> 	[string "..."]:1888: in field 'withScriptFile'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:997: in upvalue 'run_emulated_filter_chain'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:1035: in function <...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:1032>
> stack traceback:
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:225: in local 'checked_walk'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:277: in function 'run_emulated_filter'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:981: in local 'callback'
> 	[string "..."]:1888: in field 'withScriptFile'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:997: in upvalue 'run_emulated_filter_chain'
> 	...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:1035: in function <...cer/AppData/Local/Programs/Quarto/share/filters/main.lua:1032>

**Comment by schneiderpy** [comment]
I deleted everything (except figures and a small paragraph in spanish) from the new document .. now the qmd renders fine. Sorry Joel for bothering you.

**Comment by wjschne** [comment]
@schneiderpy, it is not a bother. If there is a bug in the code, I'd like to fix it. The line of code that triggers the error  is

```{lua}
floatreftext = pandoc.Inlines({pandoc.Str(figureword), pandoc.Str('\u{a0}'), pandoc.Str(fig[ct.citations[1].id])})
```
The error says that the `pandoc.Str` function was expecting a string but got `nil`. 
By default, the `figureword` variable is "Figure" in English. When `lang` is `es`, it is "Figura" However, your cross-ref, specified it as "Fig."
I discovered that apaquarto does not update the word for figure when it is specified in crossref. I belief that problem is now fixed. However, I am not sure that your original problem has been solved. Let me know if your previous document runs with the new apaquarto version.

**Comment by schneiderpy** [comment]
I had no issue with Fig. or Figura when I set lang: es .. the same for Table or Cuadro. However, it seems that Figure (Fig., Figura) and Table (Tab., Cuadro) with the corresponding number are bold in APA style.

**Comment by schneiderpy** [comment]
Table (cuadro) labels do not change to spanish .. e.g. label: tbl-models

**Comment by wjschne** [comment]
When I switch to `lang: es`, Quarto automatically changes *Table* to  *Tabla*.  Setting both the titles and prefixes for `tbl` to *Cuadro* works for me:
``` yaml
crossref: 
  tbl-title: Cuadro
  tbl-prefix: Cuadro
  fig-title: Fig.
  fig-prefix: Fig.
```

Let me know if this does not work for you.

**Comment by schneiderpy** [comment]
I have the following yaml setting:

```
crossref:
  fig-title: Figura     # (default is "Figure")
  fig-prefix: Figura
  tbl-title: Cuadro
  tbl-prefix: Cuadro
  title-delim: " "
```
Figure to Figura and tbl-title: Cuadro works fine, however, tbl-prefix seems to resolve to Tabla (as seen in text: "Tabla 1 ofrece una visión general de los modelos SARIMA utilizados.")

**Comment by schneiderpy** [comment]
It worked after updating to v. 4.3.2 .. sorry @wjschne
