### ISSUE TITLE
Error compiling example in Windows

### ISSUE THREAD

**Issue by juliandehne** [wjschne/apaquarto#77]
> Error running filter C:/Program Files/Quarto/share/filters/main.lua:
> ...rto\share\pandoc\datadir\..\..\filters\modules/typst.lua:16: attempt to index a boolean value (local 'v')
> stack traceback:
>         ...rto\share\pandoc\datadir\..\..\filters\modules/typst.lua:36: in function 'modules/typst.function_call'
>         (...tail calls...)
>         [C]: in ?
>         [C]: in method 'walk'
>         C:/Program Files/Quarto/share/filters/main.lua:557: in function <C:/Program Files/Quarto/share/filters/main.lua:546>
>         (...tail calls...)
>         C:/Program Files/Quarto/share/filters/main.lua:1334: in local 'callback'
>         C:/Program Files/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
>         C:/Program Files/Quarto/share/filters/main.lua:1388: in function <C:/Program Files/Quarto/share/filters/main.lua:1385>
> stack traceback:
>         C:/Program Files/Quarto/share/filters/main.lua:557: in function <C:/Program Files/Quarto/share/filters/main.lua:546>
>         (...tail calls...)
>         C:/Program Files/Quarto/share/filters/main.lua:1334: in local 'callback'
>         C:/Program Files/Quarto/share/filters/main.lua:1352: in upvalue 'run_emulated_filter_chain'
>         C:/Program Files/Quarto/share/filters/main.lua:1388: in function <C:/Program Files/Quarto/share/filters/main.lua:1385>

# Environment

- R: version.string R version 4.4.0 (2024-04-24 ucrt)
- Python: Python 3.12.4

**Comment by juliandehne** [comment]
Instead of running this with the example.qmd, I created an index.qmd file and copied the contents. It works except for $\latex$ which is interpreted as the latex math environment instead of marking this as latex code.

**Comment by wjschne** [comment]
In a current release of apaquarto, these lines replace any instance of $\LaTeX$ with plain text `LaTeX`. Can you verify that you are using the most recent version of apaquarto?

* https://github.com/wjschne/apaquarto/blob/a33450affa6d78c3da941e2dd625353015495fff/_extensions/apaquarto/typst/formattypst.lua#L9-L20

**Comment by juliandehne** [comment]
I seem to be on the correct version. For me, this is not critical. If you want, we can close the issue.
