### ISSUE TITLE
integrating complex caption with apa-note for figures and tables

### ISSUE THREAD

**Issue by filippogambarota** [wjschne/apaquarto#84]
In quarto there is the possibility to write complex captions as https://github.com/quarto-dev/quarto-cli/issues/1959#issuecomment-1774199261. Is this compatible with adding also apa-note in some ways?

**Comment by wjschne** [comment]
Yes, apa-note works with this kind of caption:

````
:::{#tbl-mytable apa-note="This is a note."}

```{r}
# code for table
```
Complex *caption* $(n = 20)$ 
:::
````
