### ISSUE TITLE
Wrong numbering when using complex tables captions

### ISSUE THREAD

**Issue by filippogambarota** [wjschne/apaquarto#85]
Related to #84, When trying to insert two tables as:

````
:::{#tbl-mytable apa-note="This is a note."}

```{r}
# code for table
```
Complex *caption* $(n = 20)$ 
:::
````

The numbering is Table 1 for the first one and Table 3 for the second one. Below a reproducible example (output in pdf):

````
<!-- Deafult Apaquarto YAML above -->

# Section 1

:::{#tbl-mytable1 apa-note="This is a note."}

```{r}
library(flextable)
flextable(iris[1:5, ])
```
Complex *caption* $(n = 20)$ 
:::

:::{#tbl-mytable2 apa-note="This is a note."}

```{r}
library(flextable)
flextable(iris[1:5, ])
```
Complex *caption* $(n = 20)$ 
:::
````
The same code in a standard Quarto document works correctly.

**Comment by wjschne** [comment]
This is a more general problem with all tables that use the longtable package. It appears to be a result of a change in longtable such that the table counter is used differently. I will need to figure this out.

**Comment by wjschne** [comment]
I think it is fixed now. Let me know.
