### ISSUE TITLE
One- and two-column figures in jou mode?

### ISSUE THREAD

**Issue by ihrke** [wjschne/apaquarto#91]
Thanks so much for an awesome package, I really enjoy using it!
For writing papers, I typically use the `man` option, so this has not super high priority for me. However, I noticed, that when I switch to `jou`, my figures which I typically design to be full-page (i.e., two-column figures), are assumed to fit into a single column and they therefore completely mess up the page, see screenshot:

<img width="843" alt="image" src="https://github.com/user-attachments/assets/5d4a1063-0438-47b1-a352-a0b6648f52a8">

Is there any way I can specify that the figure should be interpreted to span both columns?

**Comment by wjschne** [comment]
Thanks!

Yes, that is possible. Set the `apa-twocolumn` code chunk option to `true`. See example [here](https://wjschne.github.io/apaquarto/writing.html#tables-and-figures-spanning-two-columns-in-journal-mode-.pdf).

**Comment by ihrke** [comment]
Ah, perfect! Sorry for not reading the docs properly 😅
